name: 'pyodide-buildpackage-action'
description: 'Build pyodide packages in GitHub Actions'
inputs:
  meta-yml-path:
    description: 'Path of the meta.yml file'
    required: false
    default: 'meta.yml'
  pyodide-tag:
    description: 'Pyodide tag or branch to use'
    required: false
    default: 'main'
  output-dir:
    description: 'Directory for output wheel'
    required: false
    default: 'wheelhouse'
runs:
  using: 'docker'
  image: docker://pyodide/pyodide-env:20220525-py310-chrome102-firefox100
  entrypoint: entrypoint.sh
  args:
      - ${{ inputs.meta-yml-path }}
      - ${{ inputs.pyodide-tag }}
      - ${{ inputs.output-dir }}