name: "pyodide-buildpackage-action"
description: "Build pyodide packages in GitHub Actions"
inputs:
  meta-yaml-path:
    description: "Path of the meta.yaml file"
    required: false
    default: "meta.yaml"
  pyodide-tag:
    description: "Pyodide tag or branch to use"
    required: false
    default: "0.20.0"
  output-dir:
    description: "Directory for output package wheel"
    required: false
    default: "wheelhouse"
  all-wheels-output-dir:
    description: "Directory for all built wheels"
    required: false
    default: "wheelhouse-all"
  package-name:
    description: "Name of the package being built (default: repository name; needs to be set when building a URL)"
    required: false
    default: "None"
  build-tag:
    description: "When building the current repository, name of the branch/tag/SHA to build (default: commit's SHA); set either this or build-url (neither defaults to current SHA)"
    required: false
    default: "None"    
  build-url:
    description: "URL of package to build (e.g., https://github.com/jobovy/galpy/archive/main.tar.gz); set either this or build-tag (neither defaults to current SHA)"
    required: false
    default: "None"    
  build-deps:
    description: "Whether or not to build runtime Python dependencies (True/False)"
    required: false
    default: "False" 
runs:
  using: "composite"
  steps:
    - name: Build pyodide
      uses: ./actions/build-pyodide
      with:
        pyodide-tag: ${{ inputs.pyodide-tag }}
    - name: Build package
      uses: ./actions/build-package
      with: 
        meta-yaml-path: ${{ inputs.meta-yaml-path }}
        output-dir: ${{ inputs.output-dir }}
        package-name: ${{ inputs.package-name }}
        build-tag: ${{ inputs.build-tag }}
        build-url: ${{ inputs.build-url }}
        all-wheels-output-dir: ${{ inputs.all-wheels-output-dir }}
        build-deps: ${{ inputs.build-deps }}