name: "build-package"
description: "Build pyodide package"
inputs:
  output-dir:
    description: "Directory for output package wheel"
    required: false
    default: "wheelhouse"
  all-wheels-output-dir:
    description: "Directory for all built wheels"
    required: false
    default: "wheelhouse-all"
runs:
  using: "docker"
  image: Dockerfile
  args:
      - ${{ inputs.output-dir }}
      - ${{ inputs.all-wheels-output-dir }}