name: "build-meta"
description: "Build pyodide meta.yml for use in build-package"
inputs:
  meta-yaml-path:
    description: "Path of the meta.yaml file"
    required: false
    default: "meta.yaml"
  package-name:
    description: "Name of the package being built (default: repository name; needs to be set when building a URL)"
    required: false
    default: "None"
  build-tag:
    description: "When building the current repository, name of the branch/tag/SHA to build (default: commit's SHA); set either this or build-url (neither defaults to current SHA)"
    required: false
    default: "None"    
  build-url:
    description: "URL of package to build (e.g., https://github.com/jobovy/galpy/archive/main.tar.gz); set either this or build-tag (neither defaults to current SHA)"
    required: false
    default: "None"    
  build-deps:
    description: "Whether or not to build runtime Python dependencies (True/False)"
    required: false
    default: "False" 
runs:
  using: "docker"
  image: Dockerfile
  args:
      - ${{ inputs.meta-yaml-path }}
      - ${{ inputs.package-name }}
      - ${{ inputs.build-tag }}
      - ${{ inputs.build-url }}
      - ${{ inputs.build-deps }}