name: "build-pyodide"
description: "Build pyodide"
inputs:
  pyodide-tag:
    description: "Pyodide tag or branch to use"
    required: false
    default: "0.20.0"
runs:
  using: "docker"
  image: Dockerfile
  args:
      - ${{ inputs.pyodide-tag }}